Fix - Replacing Dropdown Field with Record Finder for Improved User E…
OFFLINE-GmbH/oc-mall-plugin pull request #996
Opened 2023-02-01 13:04 UTC by xyzqtc

…xperience

Record finder widget works better when having a big number of customers. The form isnt drawn because of the dropdown field.

2023-02-01 13:20 UTC, tobias-kuendig requested changes

2023-02-01 13:20 UTC, tobias-kuendig commented on models/address/fields.yaml
> +        label: Customer
```suggestion
        label: 'offline.mall::lang.order.customer'
```

Let's use the original label here.

2023-02-01 13:23 UTC, xyzqtc reviewed
Thanks!

2023-02-01 13:56 UTC, merged

2023-03-07 16:26 UTC, xyzqtc commented
@tobias-kuendig I got some errors like "column name is missing", probably because User columns.yaml has name field and customer model is missing name column. Maybe it will be better if we define customer columns.yaml file for future uses?